server:
  port: 8084

spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=chinook_payment;encrypt=false;trustServerCertificate=true
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
