spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: catalog-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=chinook_catalog;encrypt=false

server:
  port: 8081
