spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: customer-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=chinook_customer;encrypt=false

server:
  port: 8082
