spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: invoice-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=chinook_invoice;encrypt=false

server:
  port: 8083

application:
  services:
    customer-service:
      url: ${CUSTOMER_SERVICE_URL:http://localhost:8082}
    catalog-service:
      url: ${CATALOG_SERVICE_URL:http://localhost:8081}
